### ISSUE TITLE
CSV and PDF export issues

### ISSUE THREAD

**Issue by wilayahapps** [MrReSc/Headi#19]
Currently wo dont see any option to add 'trigger' to respective pain except from description

**Comment by MrReSc** [comment]
Yes, it is like that.
What would be your suggestion? 
Pull repquest are of course welcome.

**Comment by wilayahapps** [comment]
My suggestion is that the app databse should have one more coloum stating the trigger or root cause.

Eg: I got headache but it was caused by stress etc

**Comment by MrReSc** [comment]
Oh, I see.
The idea is good. If I find the time, I might implement it. In the meantime, you should use the "Description" field.

Or you can do the extension yourself and open a PR. Since I have very little time for the project at the moment, I would appreciate help.

**Comment by dakomi** [comment]
I think this would be great! It's one of the main things asked by doctors, too. 

Using the description box is definitely an option.

Though, when using the description for more than just 7-10 words in pdf output, less in csv output, it gets messy. (exporting for myself or doctor) 

I think these would be relatively easy fixes, though I'll admit I don't know any programming.

For pdf, the description all flows as one line, so fixing the export to break line at the right point is all that's needed.

For csv, it seems to split the description into a new cell on each occurrence of a comma or full stop. Adding some kind of exclusion to this rule for the description cell should fix it?


I think this could be a nice tool to have, as someone with chronic migraine, as the project grows. I understand its a personal project and not having time, of course. 
Thank you for sharing this!

**Comment by dakomi** [comment]
Of course, I could use shorter notes without commas or full stops (possibly other punctuation/symbols), but the length between appointments can be long, and some migraines are more significant or nuanced than others

**Comment by MrReSc** [comment]
Thank you for your interesting comment and sorry for the late reply.

I think the most sensible thing is to expand the database with the triggers, but as I said, unfortunately I still don't have the time.

Can you describe the CSV / PDF export in a new issue? This definitely needs to be fixed.

**Comment by MrReSc** [comment]
Exporting the CSV file can be easily fixed.

The line break in the PDF is more difficult to realize, because the generation of the PDF is not quite trivial. All lines and images are calculated and drawn dynamically. So that the overflow no longer happens, I will limit the number of characters in the PDF output. This is only a cometical correction. The data is basically still there. If I find time, I can correct it.

![grafik](https://user-images.githubusercontent.com/24952268/158005278-a16ed91e-0838-41e5-83b8-84dbd503e52c.png)
